### ISSUE TITLE
No rule to make target `../loudmouth/.deps/lm-data-objects.Po'.

### ISSUE THREAD

**Issue by l29ah** [mcabber/loudmouth#16] opened 2015-02-18 17:50 UTC
Making all in tests
make[2]: Entering directory `/tmp/nd/loudmouth/tests'
Makefile:477: ../loudmouth/.deps/lm-data-objects.Po: No such file or directory
make[2]: *** No rule to make target `../loudmouth/.deps/lm-data-objects.Po'.  Stop.
make[2]: Leaving directory `/tmp/nd/loudmouth/tests'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/nd/loudmouth'
make: *** [all] Error 2

There's lm-data-objects.Plo tho.
Compiles fine if configured with --disable-dependency-tracking.

**Comment by languitar** [comment] 2015-07-06 15:41
Same here

**Comment by McKael** [comment] 2015-11-06 17:31
This is caused by commit f22dd6326a676f37 AFAICS.

**Comment by mcabber** [comment] 2016-02-04 20:31
... and was fixed in 190c4fba. Thanks Michael!

**Closed by mcabber** 2016-02-04 20:31 UTC
